### ISSUE TITLE
Failed rendering front end

### ISSUE THREAD

**Issue by lordfarhan** [jeremykenedy/larablog#10]
I tried to upload on shared hosting, it worked but didn't show the front end just like in the localhost.

**Comment by jeremykenedy** [comment]
That’s an issue with your hosting environment, I would google using Laravel on shared hosting.

**Comment by lordfarhan** [comment]
Thanks for your fast respond sir

**Comment by jeremykenedy** [comment]
No problem, shared hosting is tricky.
