### ISSUE TITLE
ErrorException htmlspecialchars() expects parameter 1 to be string

### ISSUE THREAD

**Issue by robinmatus** [jeremykenedy/larablog#14]
From the project root folder I run php artisan serve, so I go to the Chrome browser and open the default URL (http://127.0.0.1:8000/) and got the following exception:
![e1](https://user-images.githubusercontent.com/29550650/74095688-e505f700-4ab9-11ea-8d3e-9be3a8315aa6.png)
![e2](https://user-images.githubusercontent.com/29550650/74095692-e9321480-4ab9-11ea-86fd-d90f40722cf5.png)

**Comment by jeremykenedy** [comment]
Seems like an environmental issue or something was missed in the installation instructions.
