### ISSUE TITLE
can't scroll down

### ISSUE THREAD

**Issue by trongtri0705** [jeremykenedy/larablog#8]
![screenshot 7](https://user-images.githubusercontent.com/13271068/53295872-472d0400-3837-11e9-9078-2a35915090b8.png)
Please help me!
I'm too bad at js, css, I can't find the problem. I've run the command 'npm run production' yet

**Comment by jeremykenedy** [comment]
I’m unable to replicate the issue.
What’s the browser?

**Comment by trongtri0705** [comment]
I tried all common browsers for win like chrome, firefox and IE.. but scrollbar didnt show and can't scroll

**Comment by jeremykenedy** [comment]
I cannot replicate the issue.

https://s3.amazonaws.com/stackoverflow-images/scroll.gif

**Comment by lordfarhan** [comment]
same issue

**Comment by Kennysleiche** [comment]
same here. using up to date google chrome.

**Comment by jeremykenedy** [comment]
Since I am unable to replicate and the dashboard using an out the box framework. You may want to raise this issue with the repo: https://github.com/creativetimofficial/paper-dashboard

**Comment by azhariejaya** [comment]
how to fix this issue? I have same problem, can't scroll down
